# -*- coding: utf-8 -*-
"""Business_Apps_Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17M4R2c-grBm8J35aBweWC4txjsV6Vi8g

Following is the dataset preprocessing
"""

import pandas as pd

df=pd.read_csv('amazon.csv')
df

df.head()

df.shape

# Check for missing values
def check_missing_values(dataframe):
    return dataframe.isnull().sum()

print(check_missing_values(df))
df[df.rating_count.isnull()]

# Remove rows with missing values in the rating_count column
df.dropna(subset=['rating_count'], inplace=True)
print(check_missing_values(df))

# Check for duplicates
def check_duplicates(dataframe):
    return dataframe.duplicated().sum()

print(check_duplicates(df))

# Check data types
def check_data_types(dataframe):
    return dataframe.dtypes

print(check_data_types(df))

df['discounted_price'] = df['discounted_price'].astype(str).str.replace('₹', '').str.replace(',', '').astype(float)
df['actual_price'] = df['actual_price'].astype(str).str.replace('₹', '').str.replace(',', '').astype(float)
df['discount_percentage'] = df['discount_percentage'].astype(str).str.replace('%','').astype(float)/100

# The rating column has a value with an incorrect character, so we will exclude the row to obtain a clean dataset.
count = df['rating'].str.contains('\|').sum()
print(f"Total de linhas com '|' na coluna 'rating': {count}")
df = df[df['rating'].apply(lambda x: '|' not in str(x))]
count = df['rating'].str.contains('\|').sum()
print(f"Total de linhas com '|' na coluna 'rating': {count}")

df['rating'] = df['rating'].astype(str).str.replace(',', '').astype(float)
df['rating_count'] = df['rating_count'].astype(str).str.replace(',', '').astype(float)

print(check_data_types(df))

# Creating the column "rating_weighted"
df['rating_weighted'] = df['rating'] * df['rating_count']

df['sub_category'] = df['category'].astype(str).str.split('|').str[-1]
df['main_category'] = df['category'].astype(str).str.split('|').str[0]

df.columns

len(df)

df.head()

"""Data visualization"""

import matplotlib.pyplot as plt

# Analyzing distribution of products by main category
main_category_counts = df['main_category'].value_counts()[:30] # Select only the top 30 main categories.
plt.bar(range(len(main_category_counts)), main_category_counts.values)
plt.ylabel('Number of Products')
plt.title('Distribution of Products by Main Category (Top 30)')
plt.xticks(range(len(main_category_counts)), '') # hide X-axis labels
plt.show()

# Top 30 main categories
top_main_categories = pd.DataFrame({'Main Category': main_category_counts.index, 'Number of Products': main_category_counts.values})
print('Top 30 main categories:')
print(top_main_categories.to_string(index=False))

# Analyzing distribution of products by last category
sub_category_counts = df['sub_category'].value_counts()[:30] # Select only the top 30 last categories.
plt.bar(range(len(sub_category_counts)), sub_category_counts.values)
plt.ylabel('Number of Products')
plt.title('Distribution of Products by Sub Category (Top 30)')
plt.xticks(range(len(sub_category_counts)), '') # hide X-axis labels
plt.show()

# Top 30 sub categories
top_sub_categories = pd.DataFrame({'Sub Category': sub_category_counts.index, 'Number of Products': sub_category_counts.values})
print('Top 30 sub categories:')
print(top_sub_categories.to_string(index=False))

# Analyze the distribution of customer ratings using a histogram.
# Plot histogram
plt.hist(df['rating'])
plt.xlabel('Rating')
plt.ylabel('Number of Reviews')
plt.title('Distribution of Customer Ratings')
plt.show()

# Create table with values per cluster
bins = [0, 1, 2, 3, 4, 5] # Define bin edges
dforginal=df
df = df.copy()
df.loc[:, 'cluster'] = pd.cut(
    df['rating'],
    bins=[0,1,2,3,4,5],
    include_lowest=True,
    labels=['0-1','1-2','2-3','3-4','4-5']
)

# value_counts + reset_index
counts = df['cluster'].value_counts().reset_index()
# now counts.columns maybe ['index', 'cluster']
counts.columns = ['Cluster', 'Number of Reviews']
table = counts.sort_values('Cluster')

print(table)

# Calculate the top main categories
top = df.groupby(['main_category'])['rating'].mean().sort_values(ascending=False).head(10).reset_index()

# Create a bar plot
plt.bar(top['main_category'], top['rating'])

# Add labels and title
plt.xlabel('main_category')
plt.ylabel('Rating')
plt.title('Top main_category by Rating')

# Rotate x-axis labels
plt.xticks(rotation=90)

# Show the plot
plt.show()
ranking = df.groupby('main_category')['rating'].mean().sort_values(ascending=False).reset_index()
print(ranking)

# Calculate the top sub categories
top = df.groupby(['sub_category'])['rating'].mean().sort_values(ascending=False).head(10).reset_index()

# Create a bar plot
plt.bar(top['sub_category'], top['rating'])

# Add labels and title
plt.xlabel('sub_category')
plt.ylabel('Rating')
plt.title('Top sub_category by Rating')

# Rotate x-axis labels
plt.xticks(rotation=90)

# Show the plot
plt.show()
ranking = df.groupby('sub_category')['rating'].mean().sort_values(ascending=False).reset_index()
print(ranking)

# sort the means in descending order
mean_discount_by_category = df.groupby('main_category')['discount_percentage'].mean()
mean_discount_by_category = mean_discount_by_category.sort_values(ascending=True)

# create the horizontal bar chart
plt.barh(mean_discount_by_category.index, mean_discount_by_category.values)
plt.title('Discount Percentage by Main Category')
plt.xlabel('Discount Percentage')
plt.ylabel('Main Category')
plt.show()

table = pd.DataFrame({'Main Category': mean_discount_by_category.index, 'Mean Discount Percentage': mean_discount_by_category.values})

print(table)

# sort the means in descending order
mean_discount_by_sub_category = df.groupby('sub_category')['discount_percentage'].mean().head(15)
mean_discount_by_sub_category = mean_discount_by_sub_category.sort_values(ascending=True)

# create the horizontal bar chart
plt.barh(mean_discount_by_sub_category.index, mean_discount_by_sub_category.values)
plt.title('Discount Percentage by Sub Category')
plt.xlabel('Discount Percentage')
plt.ylabel('Sub Category')
plt.show()

table = pd.DataFrame({'Sub Category': mean_discount_by_sub_category.index, 'Mean Discount Percentage': mean_discount_by_sub_category.values})

print(table)

from wordcloud import WordCloud

# Analyze the reviews by creating word clouds or frequency tables of the most common words used in the reviews.
reviews_text = ' '.join(df['review_content'].dropna().values)
wordcloud = WordCloud(width=800, height=800, background_color='white', min_font_size=10).generate(reviews_text)
plt.figure(figsize=(8, 8), facecolor=None)
plt.imshow(wordcloud)
plt.axis("off")
plt.tight_layout(pad=0)
plt.show()

# Filter the dataframe to include only products with a rating lower than 2
low_rating_df = df[df['rating'] > 4.0]

# Create a string of all the reviews for these products
reviews_text = ' '.join(low_rating_df['review_content'].dropna().values)

# Generate the wordcloud
wordcloud = WordCloud(width=800, height=800, background_color='white', min_font_size=10).generate(reviews_text)

# Plot the wordcloud
plt.figure(figsize=(8, 8), facecolor=None)
plt.imshow(wordcloud)
plt.axis("off")
plt.tight_layout(pad=0)
plt.show()

"""Correlation & Fraudulent Review Identification"""

# Perform statistical analysis to identify any correlations between different features, such as the relationship between product price and customer rating. - Zoe
# Drop non-numeric columns
numeric_cols = df.select_dtypes(include=['float64', 'int64'])
correlation_matrix = numeric_cols.corr()

# Print the correlation matrix
print(correlation_matrix)

# Analyze Correlation to leverage data relationships
import seaborn as sns
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm')
plt.title('Correlation Matrix')
plt.show()

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['user_id_encoded'] = le.fit_transform(df['user_id'])

# Create a new dataframe with the user_id frequency table
freq_table = pd.DataFrame({'User ID': df['user_id_encoded'].value_counts().index, 'Frequency': df['user_id_encoded'].value_counts().values})

# Display the dataframe
print(freq_table)
id_example = freq_table.iloc[0,0]
print(id_example)

# Add Fraudulent Flags
import numpy as np

# Create a new column to flag short reviews
df['review_length'] = df['review_content'].fillna('').apply(lambda x: len(x.split()))
df['is_short_review'] = np.where(df['review_length'] < 5, 1, 0)

# Flag high discount
df['is_high_discount'] = np.where(df['discount_percentage'] >= 0.9, 1, 0)

# Flag high rating with few ratings
df['is_rating_suspicious'] = np.where((df['rating'] >= 4.5) & (df['rating_count'] < 5), 1, 0)

# Flag duplicate reviews (exact matches)
df['is_duplicate_review'] = df.duplicated(subset=['review_content'], keep=False).astype(int)

# Final fraud flag
df['fraudulent'] = np.where(
    (df['is_short_review'] == 1) |
    (df['is_high_discount'] == 1) |
    (df['is_rating_suspicious'] == 1) |
    (df['is_duplicate_review'] == 1),
    1, 0
)

# Total number of reviews
total_reviews = df.shape[0]

# Number of high-discount products
high_discount_count = df[df['discount_percentage'] >= 0.9].shape[0]

# Number of short reviews
short_review_count = df[df['review_length'] < 5].shape[0]

# Total flagged as fraudulent
fraudulent_count = df[df['fraudulent'] == 1].shape[0]

# Percentage of fraudulent entries
fraudulent_percentage = (fraudulent_count / total_reviews) * 100

# Print results
print(f"Total reviews: {total_reviews}")
print(f"Products with >= 90% discount: {high_discount_count}")
print(f"Reviews with < 5 words: {short_review_count}")
print(f"Fraudulent entries identified: {fraudulent_count} ({fraudulent_percentage:.2f}%)")

"""Recommendation system"""

# Reset the index in clean_df and make sure the indices align with the TF-IDF matrix.
# Filter out fraudulent reviews
clean_df = df[df['fraudulent'] == 0].reset_index(drop=True)

def recommend_products(df, user_id_encoded):
    from sklearn.feature_extraction.text import TfidfVectorizer
    from sklearn.metrics.pairwise import cosine_similarity
    import pandas as pd

    tfidf = TfidfVectorizer(stop_words='english')
    df['about_product'] = df['about_product'].fillna('')
    tfidf_matrix = tfidf.fit_transform(df['about_product'])

    # Get user history from the new filtered df
    user_history = df[df['user_id_encoded'] == user_id_encoded]

    # Check if user has history
    if user_history.empty:
        print("No purchase history found.")
        return None

    # Get the new positions in the TF-IDF matrix
    indices = user_history.index.tolist()

    cosine_sim_user = cosine_similarity(tfidf_matrix[indices], tfidf_matrix)

    # Get product names from the filtered df
    products = df.iloc[indices]['product_name']
    index_series = pd.Series(products.index, index=products)

    similarity_scores = list(enumerate(cosine_sim_user[-1]))
    similarity_scores = [(i, score) for (i, score) in similarity_scores if i not in indices]

    similarity_scores = sorted(similarity_scores, key=lambda x: x[1], reverse=True)

    top_products = [i[0] for i in similarity_scores[1:6]]
    recommended_products = df.iloc[top_products]['product_name'].tolist()
    scores = [similarity_scores[i][1] for i in range(1, 6)]

    results_df = pd.DataFrame({
        'Id Encoded': [user_id_encoded] * 5,
        'Recommended Product': recommended_products,
        'Recommendation Score': scores
    })

    return results_df
def evaluate_accuracy(df):
    """
    For each user set their last payment as validation to chech whether it's in their recommandation
    """
    hits = 0
    n_users = 0
    for u in df['user_id_encoded'].unique():
        user_df = df[df['user_id_encoded'] == u]
        if len(user_df) < 2:
            continue
        holdout = user_df.iloc[-1]
        train_df = df.drop(holdout.name)
        recs = recommend_products(train_df, u)
        if recs is None:
            continue
        if holdout['product_name'] in recs:
            hits += 1
        n_users += 1
    acc_at_5 = hits / n_users if n_users > 0 else 0.0
    print(f"Validated on {n_users} users, Accuracy@5 = {acc_at_5:.4f}")
    #return acc_at_5
# Re-run recommendation
print(recommend_products(clean_df, user_id_encoded=893))
evaluate_accuracy(clean_df)

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.utils import to_categorical
from sklearn.metrics import roc_curve, auc

def recommend_products_dl(df,user_id_encoded,max_num_words=10000,max_seq_len=100,embedding_dim=128,lstm_units=64,batch_size=32,epochs=256):
    """
    Use a deep-learning text‐classification model to predict the top‐5 products
    for a given user. Split the data 60% train / 30% validation / 10% test.
    """

    # —— 1. Preprocess & filter out fraud ——
    df = df[df['fraudulent'] == 0].reset_index(drop=True)
    df['about_product'] = df['about_product'].fillna('')

    # —— 2.  Label encoding ——
    le = LabelEncoder()
    df['product_label'] = le.fit_transform(df['product_name'])
    num_classes = len(le.classes_)

    # —— 3. Tokenize text ——
    tokenizer = Tokenizer(num_words=max_num_words, oov_token='<OOV>')
    tokenizer.fit_on_texts(df['about_product'])
    sequences = tokenizer.texts_to_sequences(df['about_product'])
    X = pad_sequences(sequences, maxlen=max_seq_len, padding='post')

    # —— 4.  Build one-hot targets ——
    y = to_categorical(df['product_label'], num_classes=num_classes)

    # —— 5. 60-30-10 split ——
    X_temp, X_test, y_temp, y_test, df_temp, df_test = train_test_split(
      X, y, df,
      test_size=0.10,
      random_state=42,
      stratify=None  # dont use this -> stratify=df['product_label'] some label only have one
    )
    val_ratio = 0.30 / 0.90
    X_train, X_val, y_train, y_val, df_train, df_val = train_test_split(
      X_temp, y_temp, df_temp,
      test_size=val_ratio,
      random_state=42,
      stratify=None  # dont use this -> stratify=df['product_label'] some label only have one
    )


    # —— 6. Build Keras model ——
    model = Sequential([
        Embedding(input_dim=max_num_words,
                  output_dim=embedding_dim,
                  input_length=max_seq_len),
        LSTM(lstm_units),
        Dense(256, activation='relu'),
        Dense(128, activation='relu'),
        Dense(64, activation='relu'),
        Dense(32, activation='relu'),
        Dense(num_classes, activation='softmax')
    ])
    model.compile(
        loss='categorical_crossentropy',
        optimizer='adam',
        metrics=['accuracy']
    )

    # —— 7. Train & Validatioon ——
    history=model.fit(
        X_train, y_train,
        validation_data=(X_val, y_val),
        epochs=epochs,
        batch_size=batch_size
    )
    # Plot Training Curve
    def plot_training_curves(history):
        plt.figure(figsize=(12, 5))

        # Plot Accuracy
        plt.subplot(1, 2, 1)
        plt.plot(history.history['accuracy'], label='Training Accuracy')
        plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
        plt.title('Training and Validation Accuracy')
        plt.xlabel('Epochs')
        plt.ylabel('Accuracy')
        plt.legend()

        # Plot Loss
        plt.subplot(1, 2, 2)
        plt.plot(history.history['loss'], label='Training Loss')
        plt.plot(history.history['val_loss'], label='Validation Loss')
        plt.title('Training and Validation Loss')
        plt.xlabel('Epochs')
        plt.ylabel('Loss')
        plt.legend()

        plt.tight_layout()
        plt.show()

    plot_training_curves(history)

    # Evaluate on test set
    test_loss, test_acc = model.evaluate(X_test, y_test, verbose=0)
    print(f"Test Accuracy: {test_acc:.4f}")

    # Plot ROC Curve
    def plot_roc_curve(y_true, y_pred, num_classes):
        plt.figure(figsize=(10, 7))
        for i in range(num_classes):
            fpr, tpr, _ = roc_curve(y_true[:, i], y_pred[:, i])
            roc_auc = auc(fpr, tpr)
            plt.plot(fpr, tpr, label=f'Class {i} (AUC = {roc_auc:.2f})')

        plt.plot([0, 1], [0, 1], 'k--')
        plt.title('ROC Curve')
        plt.xlabel('False Positive Rate')
        plt.ylabel('True Positive Rate')
        plt.legend(loc='lower right')
        plt.show()

    y_pred_test = model.predict(X_test)
    plot_roc_curve(y_test, y_pred_test, num_classes)
    val_acc = history.history['val_accuracy'][-1]
    print(f"Validation Accuracy (last epoch): {val_acc:.4f}")
    test_loss, test_acc = model.evaluate(X_test, y_test, verbose=0)
    print(f"Test Accuracy: {test_acc:.4f}")
    # —— 8.  Recommend for one user ——
    # last history record
    user_hist = df[df['user_id_encoded'] == user_id_encoded]
    if user_hist.empty:
        print("No purchase history found.")
        return None

    last_text = user_hist['about_product'].iloc[-1]
    seq = tokenizer.texts_to_sequences([last_text])
    seq = pad_sequences(seq, maxlen=max_seq_len, padding='post')

    # predict
    probs = model.predict(seq)[0]
    # get rid of already purchased
    hist_labels = set(user_hist['product_label'])
    ranked = [i for i in probs.argsort()[::-1] if i not in hist_labels]
    top5 = ranked[:5]

    # back to the name
    rec_products = le.inverse_transform(top5)
    rec_scores   = [probs[i] for i in top5]

    import pandas as pd
    results_df = pd.DataFrame({
        'Id Encoded': [user_id_encoded] * len(top5),
        'Recommended Product': rec_products,
        'Recommendation Score': rec_scores
    })
    return results_df

recommend_products_dl(clean_df, user_id_encoded=893)

import pandas as pd

# Remove currency symbols and convert columns to numeric
df['discounted_price'] = df['discounted_price'].astype(str).str.replace('₹', '', regex=False).str.replace(',', '', regex=False)
df['actual_price'] = df['actual_price'].astype(str).str.replace('₹', '', regex=False).str.replace(',', '', regex=False)
df['discount_percentage'] = df['discount_percentage'].astype(str).str.replace('%', '', regex=False)

# Convert to numeric, coerce errors to NaN
df['discounted_price'] = pd.to_numeric(df['discounted_price'], errors='coerce')
df['actual_price'] = pd.to_numeric(df['actual_price'], errors='coerce')
df['discount_percentage'] = pd.to_numeric(df['discount_percentage'], errors='coerce')

# Clean and convert rating and rating_count
df['rating'] = pd.to_numeric(df['rating'], errors='coerce')
df['rating_count'] = df['rating_count'].astype(str).str.replace(',', '', regex=False)
df['rating_count'] = pd.to_numeric(df['rating_count'], errors='coerce')

# Drop rows with missing key values
df.dropna(subset=['discounted_price', 'actual_price', 'discount_percentage', 'rating', 'rating_count'], inplace=True)

# Create estimated revenue column
df['estimated_revenue'] = df['discounted_price'] * df['rating_count']

"""Customer segmentation"""

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# Select features for clustering
features = df[['discounted_price', 'discount_percentage', 'rating', 'rating_count', 'estimated_revenue']]

# Standardize features
scaler = StandardScaler()
scaled_features = scaler.fit_transform(features)

# Apply KMeans clustering
kmeans = KMeans(n_clusters=4, random_state=42, n_init=10)
df['segment'] = kmeans.fit_predict(scaled_features)

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
sns.scatterplot(data=df, x='discount_percentage', y='estimated_revenue', hue='segment', palette='Set1')
plt.title('Customer Segments based on Discount vs. Revenue')
plt.xlabel('Discount Percentage')
plt.ylabel('Estimated Revenue')
plt.legend(title='Segment')
plt.show()

segment_summary = df.groupby('segment').agg({
    'estimated_revenue': 'sum',
    'discounted_price': 'mean',
    'discount_percentage': 'mean',
    'rating': 'mean',
    'rating_count': 'mean',
    'product_id': 'count'
}).reset_index()

# Rename columns for clarity
segment_summary.rename(columns={
    'estimated_revenue': 'Total Revenue',
    'discounted_price': 'Avg Price',
    'discount_percentage': 'Avg Discount %',
    'rating': 'Avg Rating',
    'rating_count': 'Avg Review Count',
    'product_id': 'Product Count'
}, inplace=True)

# Display summary
segment_summary

plt.figure(figsize=(10, 6))
sns.barplot(x='segment', y='Total Revenue', data=segment_summary, palette='Blues_d')
plt.title('Total Revenue by Segment')
plt.xlabel('Segment')
plt.ylabel('Total Estimated Revenue')
plt.show()

"""Price strategy"""

import matplotlib.pyplot as plt
import seaborn as sns

# Create a profitability proxy: estimated revenue
df['revenue_estimate'] = df['discounted_price'] * df['rating_count']

# Scatter plot: Rating vs Discounted Price
sns.scatterplot(data=df, x='rating', y='discounted_price', hue='main_category', alpha=0.7)
plt.title("Discounted Price vs Rating by Main Category")
plt.show()

# Scatter plot: Rating vs Revenue Estimate
sns.scatterplot(data=df, x='rating', y='revenue_estimate', hue='main_category', alpha=0.7)
plt.title("Estimated Revenue vs Rating by Main Category")
plt.show()

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

# Select relevant features
X = df[['actual_price', 'discount_percentage', 'rating', 'rating_count', 'rating_weighted']]
y = df['discounted_price']

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train model
model = LinearRegression()
model.fit(X_train, y_train)

# Evaluate
y_pred = model.predict(X_test)
print("R² Score:", r2_score(y_test, y_pred))
import numpy as np
print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))

# Focus on high-rated products
top_rated = df[df['rating'] >= 4.5]

# Group by price bins and calculate total revenue
top_rated['price_bin'] = pd.cut(top_rated['discounted_price'], bins=10)
revenue_by_price = top_rated.groupby('price_bin')['revenue_estimate'].sum()

# Plot
revenue_by_price.plot(kind='bar', figsize=(10,5), title='Revenue by Price Bins for Highly Rated Products')
plt.ylabel("Total Revenue (INR)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

top_products = df[['product_name', 'revenue_estimate']].sort_values(by='revenue_estimate', ascending=False).head(10)
sns.barplot(data=top_products, y='product_name', x='revenue_estimate', palette='viridis')
plt.title("Top 10 Revenue-Generating Products")
plt.xlabel("Estimated Revenue (₹)")
plt.ylabel("Product")
plt.tight_layout()
plt.show()

price_revenue = df.groupby(df['discounted_price'].round(-2))['revenue_estimate'].sum().reset_index()

plt.plot(price_revenue['discounted_price'], price_revenue['revenue_estimate'], marker='o')
plt.title("Total Revenue by Discounted Price (Binned)")
plt.xlabel("Discounted Price (Rounded)")
plt.ylabel("Total Revenue")
plt.grid(True)
plt.show()